### ISSUE TITLE
track NCIT and SNOMED annotations parsing

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/external-metadata-awareness#146]
Which of these would be interprested as asthma

- http://purl.bioontology.org/ontology/SNOMEDCT/195967001
- SNOMED:195967001
- SNOMEDCT:195967001
- http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C28397
- NCIT:C28397

----

https://www.ncbi.nlm.nih.gov/biosample/47276451

```yaml
biosample:
  accession: SAMN47276451
  sample_name: H81_meat
  sra_accession: SRS24331100

organism:
  name: meat metagenome
  classification:
    - unclassified entries
    - unclassified sequences
    - metagenomes
    - ecological metagenomes

package:
  type: MIMS: metagenome/environmental, food-food production facility; version 6.0

attributes:
  collection_site_geographic_feature: "meat (whole or pieces) [FOODON:03317170]"
  collection_date: "2024-12-25"
  broad_scale_environmental_context:
    - "red meat (eurofir) [FOODON:03400794]"
    - "Beef [NCIT:C71932]"
    - "piece of beef [FOODON:02000403]"
  local_scale_environmental_context: "not applicable"
  environmental_medium: "not applicable"
  food_contact_surface: "Beef [NCIT:C71932]"
  food_product_by_quality: "not applicable"
  food_product_type: "Beef [NCIT:C71932]"
  geographic_location: "Ireland"
  ifsac_category: "land animals: meat: beef"
  latitude_and_longitude: "missing"
  sample_material_type:
    - "Packs and swabs (physical object) [SNOMED:257259007]"
    - "surface wipe [OBI:0002824]"
  sample_source_material_category: "not applicable"
  sample_storage_device: "not applicable"
  sample_storage_media: "not applicable"
  facility_type: "manufacturing-processing"
  food_production_characteristics: "free-range, beef"
  food_source: "beef cattle [HSO:0000022]"
  isolation_source: "Meat 22 R17"
  animal_environment: "Animal4"
  facilities: "H"
  before_after_cleaning: "not applicable"
  environment_animal: "Animal"
  silverside: "Left Silverside"
  visiting_days_ireland: "07-May-2024"

description:
  keywords:
    - "GSC:MIxS"
    - "MIMS:6.0"

bioproject:
  accession: PRJNA1233666
  retrieve_samples_url: "https://www.ncbi.nlm.nih.gov/biosample/?term=PRJNA1233666"

submission:
  submitter: "University of Naples Federico II, Danilo Ercolini"
  submission_date: "2025-03-09"

ids:
  biosample_accession: SAMN47276451
  id: 47276451
```
